module.exports = {
  AUTH: {
    NOT_FOUND_OR_WRONG_PWD: 'NOT_FOUND_OR_WRONG_PWD',
    WRONG_AUTHORIZATION_TYPE: 'WRONG_AUTHORIZATION_TYPE',
    INVALID_AUTHORIZATION: 'INVALID_AUTHORIZATION',
    INVALID_USER: 'INVALID_USER',
    ACCESS_DENIED: 'ACCESS_DENIED',
    AUTHORIZATION_REQUIRED: 'AUTHORIZATION_REQUIRED',
    SESSION_EXPIRED: 'SESSION_EXPIRED'
  },
  CRUD: {
    DUPLICATE_ITEM: 'DUPLICATE_ITEM',
    INVALID_REQUEST: 'INVALID_REQUEST'
  },
  ACCOUNT: {
    INVALID_VERIFICATION_CODE: 'INVALID_VERIFICATION_CODE',
    INVALID_RESET_PASSWORD_CODE: 'INVALID_RESET_PASSWORD_CODE'
  }
}
